# permissions for end users to edit gcpgces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gcpgce-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vmstate-operator
    app.kubernetes.io/part-of: vmstate-operator
    app.kubernetes.io/managed-by: kustomize
  name: gcpgce-editor-role
rules:
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpgces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpgces/status
  verbs:
  - get
